#!/bin/bash

# Script to download data files from Dropbox (see README for more instructions)

wget https://www.dropbox.com/sh/sx5spfq76rm5149/AAA9YO9f8OUVDtddsUy9zhdea/10k-labels.out

wget https://www.dropbox.com/sh/sx5spfq76rm5149/AAD1Uk2xcd2aCuXhUV2Jfw9Ba/10k-normalized-images.out
