directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_NB_K:acc#1 RESOURCE_NAME CONV_K_W:acc#20:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:acc#1 RESOURCE_NAME CONV_K_W:acc#20:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#20 RESOURCE_NAME CONV_K_W:acc#20:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:acc RESOURCE_NAME CONV_H_SLIDE:acc#15:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_H_SLIDE:acc#15 RESOURCE_NAME CONV_H_SLIDE:acc#15:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_V_SLIDE:acc#1 RESOURCE_NAME CONV_H_SLIDE:acc#12:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:acc#1 RESOURCE_NAME CONV_H_SLIDE:acc#12:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:else:else:acc#11 RESOURCE_NAME CONV_H_SLIDE:acc#12:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_H_SLIDE:acc#12 RESOURCE_NAME CONV_H_SLIDE:acc#12:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_H_SLIDE:mul RESOURCE_NAME CONV_H_SLIDE:mul:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:else:else:mul#7 RESOURCE_NAME CONV_H_SLIDE:mul:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_H_SLIDE:acc#5 RESOURCE_NAME CONV_H_SLIDE:acc#5:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:acc#2 RESOURCE_NAME CONV_H_SLIDE:acc#5:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-1:CONV_K_H-2:CONV_K_W-2:mul#10 RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10 RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-3:CONV_K_H-3:CONV_K_W-2:mul#10 RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-3:CONV_K_H-2:CONV_K_W-2:mul#10 RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-3:CONV_K_H-1:CONV_K_W-2:mul#10 RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-2:CONV_K_H-3:CONV_K_W-2:mul#10 RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-2:CONV_K_H-2:CONV_K_W-2:mul#10 RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-2:CONV_K_H-1:CONV_K_W-2:mul#10 RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-1:CONV_K_H-3:CONV_K_W-2:mul#10 RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-2:mul#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#55 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#63 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#57 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#46 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#64 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#48 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#49 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#60 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#52 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#54 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10 RESOURCE_NAME CONV_K_D-3:CONV_K_H-3:CONV_K_W-3:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#56 RESOURCE_NAME CONV_K_W:acc#53:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#61 RESOURCE_NAME CONV_K_W:acc#53:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#53 RESOURCE_NAME CONV_K_W:acc#53:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#44 RESOURCE_NAME CONV_K_W:acc#44:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#45 RESOURCE_NAME CONV_K_W:acc#44:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#50 RESOURCE_NAME CONV_K_W:acc#44:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#51 RESOURCE_NAME CONV_K_W:acc#44:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#59 RESOURCE_NAME CONV_K_W:acc#59:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#62 RESOURCE_NAME CONV_K_W:acc#59:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#58 RESOURCE_NAME CONV_K_W:acc#58:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#65 RESOURCE_NAME CONV_K_W:acc#58:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#67 RESOURCE_NAME CONV_K_W:acc#47:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#47 RESOURCE_NAME CONV_K_W:acc#47:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-1:CONV_K_H-2:CONV_K_W-1:mul RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-1:mul:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-1:CONV_K_H-3:CONV_K_W-1:mul RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-1:mul:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-1:CONV_K_H-1:CONV_K_W-1:mul RESOURCE_NAME CONV_K_D-1:CONV_K_H-1:CONV_K_W-1:mul:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-1:CONV_K_H-3:CONV_K_W-1:acc#14 RESOURCE_NAME CONV_K_D-1:CONV_K_H-3:CONV_K_W-1:acc#14:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#26 RESOURCE_NAME CONV_K_D-1:CONV_K_H-3:CONV_K_W-1:acc#14:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-1:CONV_K_H-3:CONV_K_W-2:acc#14 RESOURCE_NAME CONV_K_D-1:CONV_K_H-3:CONV_K_W-2:acc#14:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#27 RESOURCE_NAME CONV_K_D-1:CONV_K_H-3:CONV_K_W-2:acc#14:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_D-1:CONV_K_H-3:CONV_K_W-3:acc#14 RESOURCE_NAME CONV_K_D-1:CONV_K_H-3:CONV_K_W-3:acc#14:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#28 RESOURCE_NAME CONV_K_D-1:CONV_K_H-3:CONV_K_W-3:acc#14:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#21 RESOURCE_NAME CONV_K_W:acc#21:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_NB_K:acc RESOURCE_NAME CONV_K_W:acc#21:rg
