directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_NB_K:acc#1 RESOURCE_NAME CONV_K_W:acc#11:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:acc#1 RESOURCE_NAME CONV_K_W:acc#11:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#11 RESOURCE_NAME CONV_K_W:acc#11:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_NB_K:acc#2 RESOURCE_NAME CONV_K_H:acc#1:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_H:acc#1 RESOURCE_NAME CONV_K_H:acc#1:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:acc RESOURCE_NAME CONV_H_SLIDE:acc#15:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_H_SLIDE:acc#15 RESOURCE_NAME CONV_H_SLIDE:acc#15:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#2 RESOURCE_NAME CONV_K_W:acc#2:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:oif:acc RESOURCE_NAME CONV_K_W:acc#2:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:asn(pref:pref.pref#4(6:CONV_K_W:acc RESOURCE_NAME CONV_K_W:asn(pref:pref.pref#4(6:CONV_K_W:acc:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:acc RESOURCE_NAME CONV_K_W:asn(pref:pref.pref#4(6:CONV_K_W:acc:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_V_SLIDE:acc#1 RESOURCE_NAME CONV_H_SLIDE:acc#12:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:acc#1 RESOURCE_NAME CONV_H_SLIDE:acc#12:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:else:else:acc#11 RESOURCE_NAME CONV_H_SLIDE:acc#12:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_H_SLIDE:acc#12 RESOURCE_NAME CONV_H_SLIDE:acc#12:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_H_SLIDE:acc#5 RESOURCE_NAME CONV_H_SLIDE:acc#5:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:acc#2 RESOURCE_NAME CONV_H_SLIDE:acc#5:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:if:mul RESOURCE_NAME CONV_K_W:mul#11:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:mul#11 RESOURCE_NAME CONV_K_W:mul#11:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:else:else:mul#7 RESOURCE_NAME CONV_H_SLIDE:mul:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_H_SLIDE:mul RESOURCE_NAME CONV_H_SLIDE:mul:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/CONV_K_W:acc#10 RESOURCE_NAME CONV_K_W:acc#10:rg
directive set /apply_conv/apply_conv:core/apply_conv:core:conc/PAD:for:for:else:else:acc#10 RESOURCE_NAME CONV_K_W:acc#10:rg
