# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.cache/wt [current_project]
set_property parent.project_path /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboAudio/ZyboRTOS/ip_repo [current_project]
set_property ip_output_repo /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGAMire/mire.coe
add_files /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/image.coe
read_vhdl -library RAM /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/RAM/RAM_pkg.vhd
read_vhdl -library vfixe {
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/vfixe/vfixe.vhd
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/vfixe/reduce_pack.vhd
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/vfixe/reduce_pack_boolean.vhd
}
read_vhdl -library divers {
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/divers/data_pkg.vhd
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/divers/serie_pkg.vhd
}
read_vhdl -library img {
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/img/vecteur_pkg.vhd
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/img/img_pkg.vhd
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/img/image_pkg.vhd
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/img/volume_pkg.vhd
}
read_vhdl -library io_video {
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/io_video/io_video_pkg.vhd
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/io_video/display/display_VGA_memory_read.vhd
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/io_video/display/display_synchro.vhd
}
read_vhdl -library xil_defaultlib {
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/VHDL/io_video/Zybo_VGA_Proc_RAM.vhd
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/imports/fpga/concat_rtl.vhdl
  /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/imports/hdl/design_1_wrapper.vhd
}
read_ip -quiet /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/blk_mem_mire_out/blk_mem_mire_out.xci
set_property used_in_implementation false [get_files -all /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/blk_mem_mire_out/blk_mem_mire_out_ooc.xdc]
set_property is_locked true [get_files /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/blk_mem_mire_out/blk_mem_mire_out.xci]

read_ip -quiet /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/blk_mem_mire/blk_mem_mire.xci
set_property used_in_implementation false [get_files -all /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/blk_mem_mire/blk_mem_mire_ooc.xdc]
set_property is_locked true [get_files /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/blk_mem_mire/blk_mem_mire.xci]

read_ip -quiet /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc
set_property used_in_implementation false [get_files /tp/xph3sei/xph3sei702/Documents/cnn-accelerator/fpga/vga/Zynq/Zybo/ZyboTest/ZyboVGARAMProc/ZyboVGARAMProc.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z010clg400-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
