# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/ZYBO_Master.xdc

# IP: ip/blk_mem_mire_out/blk_mem_mire_out.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_mire_out || ORIG_REF_NAME==blk_mem_mire_out}]

# IP: ip/blk_mem_mire/blk_mem_mire.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_mire || ORIG_REF_NAME==blk_mem_mire}]
