
# Loop constraints
directive set /apply_conv/core/core:rlp CSTEPS_FROM {{. == 1}}
directive set /apply_conv/core/core:rlp/main CSTEPS_FROM {{. == 4} {.. == 1}}

# IO operation constraints

# Sync operation constraints

# Real operation constraints
directive set /apply_conv/core/core:rlp/main/and CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#3 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#4 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:PAD:and CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:PAD:for:and CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:oif:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:if:PAD:for:for:if:mul CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:if:mul CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:if:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:if:write_mem(pad_input:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:oif:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:if:write_mem(pad_input:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:else:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:else:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:else:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:else:mul#7 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:else:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:else:read_mem(conv_in:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:else:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:else:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:else:else:write_mem(pad_input:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#5 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:for:for:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#7 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:PAD:and#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/PAD:PAD:and#3 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_V_SLIDE:CONV_V_SLIDE:and CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:CONV_H_SLIDE:and#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_D:CONV_K_D:and CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_H:CONV_K_H:and CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#21 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:CONV_H_SLIDE:and CSTEPS_FROM {{.. == 2}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:mul CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:mul#11 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:read_mem(pad_input:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#20 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:mul#12 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:asn(pref:pref.pref#4(6:CONV_K_W:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:mul#10 CSTEPS_FROM {{.. == 3}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#10 CSTEPS_FROM {{.. == 3}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_H:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_H:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#9 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:mux CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_W:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_D:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_D:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#11 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_H:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_H:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:else:if:acc CSTEPS_FROM {{.. == 3}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:else:mux CSTEPS_FROM {{.. == 3}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:CONV_H_SLIDE:and#3 CSTEPS_FROM {{.. == 3}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:mul CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:write_mem(conv_out:rsc.@) CSTEPS_FROM {{.. == 3}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#13 CSTEPS_FROM {{.. == 3}}
directive set /apply_conv/core/core:rlp/main/and#14 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_D:mux#4 CSTEPS_FROM {{.. == 3}}
directive set /apply_conv/core/core:rlp/main/CONV_K_D:mux#5 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_K_D:mux#6 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_V_SLIDE:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_V_SLIDE:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_V_SLIDE:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#16 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:mux#5 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:mux#6 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:acc CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/and#18 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_V_SLIDE:mux#4 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_V_SLIDE:mux CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_V_SLIDE:CONV_V_SLIDE:and#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_H_SLIDE:mux CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_V_SLIDE:CONV_V_SLIDE:and#3 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:and#2 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:mux1h#27 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#3 CSTEPS_FROM {{.. == 3}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#8 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:CONV_NB_K:mux1h CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:CONV_NB_K:mux1h#1 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:mux1h#11 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:mux1h#12 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#11 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#12 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#13 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#14 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#15 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#16 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#17 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#27 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#28 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#29 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:mux1h#33 CSTEPS_FROM {{.. == 1}}
directive set /apply_conv/core/core:rlp/main/CONV_NB_K:CONV_NB_K:mux#30 CSTEPS_FROM {{.. == 1}}

# Probe constraints
