#! /bin/bash 
# -*- coding: UTF-8 -*-
###########################################################################################
# Script de configuration pour la simulation comportementale avec 
# ModelsSIm de Mentor Graphics
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# Il est attendu que le présent script soit placé dans le sous-répertoire "config" de 
# l'arborescence du TP. La base de l'arborescence du TP est donc le répertoire parent du 
# répertoire contenant ce script. Le chemin complet (absolu) de la base de l'arborescence 
# est déterminé par le script
# /tp/outils/cheminduparent
#
# ATTENTION 
# Pour toujours obtenir le nom d'un script à l'intérieur de celui-ci, qu'il soit exécuté ou 
# sourcé, il convient d'utiliser la variable d'environnement $BASH_SOURCE. En effet, $0 
# retourne le nom de l'interpréteur de commandes utilisé. Le résultat est donc différent
# selon que le script est exécuté ou sourcé.
###########################################################################################

export TP_PATH=`pwd`
printf "\nTP_PATH (base de l'arborescence du TP) = \n%s\n\n" "$TP_PATH"

	# ATTENTION à l'ordre : en interne modelsim.ini utilise des variables définies dans
	# config_ISE et dans config_AMS
source /softslin/configCAO/Xilinx/config_ISE
source /softslin/configCAO/AMS/config_AMS
source /softslin/configCAO/MentorGraphics/licence_mentor_graphics
source /softslin/configCAO/MentorGraphics/config_ModelSim

export MODELSIM="${TP_PATH}/modelsim.ini"


