// ----------------------------------------------------------------------------
// SystemC Header for Top
//
//    HLS version: 10.0a/269363 Production Release
//       HLS date: Wed Nov  9 17:38:00 PST 2016
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 8.0a
//
//   Generated by: xph3sei702@cimeld95
// Generated date: Wed Jan 24 16:11:03 CET 2018
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// scverify_top
// top module instantiating reference design,
// DUT and comparator
// -------------------------------------
// 
#ifndef INCLUDED_SCVERIFY_TOP_H
#define INCLUDED_SCVERIFY_TOP_H

#ifndef TO_QUOTED_STRING
#define TO_QUOTED_STRING(x) TO_QUOTED_STRING1(x)
#define TO_QUOTED_STRING1(x) #x
#endif
#ifndef TOP_HDL_ENTITY
#define TOP_HDL_ENTITY apply_conv
#endif

// Hold time for the SCVerify testbench to account for the gate delay after downstream synthesis in pico second(s)
// Hold time value is obtained from 'top_gate_constraints.cpp', which is generated at the end of RTL synthesis
#ifdef CCS_DUT_GATE
extern double __scv_hold_time;
extern double __scv_hold_time_RSCID_1;
extern double __scv_hold_time_RSCID_2;
#else
double __scv_hold_time = 0.0; // default for non-gate simulation is zero
double __scv_hold_time_RSCID_1 = 0.0;
double __scv_hold_time_RSCID_2 = 0.0;
#endif


#include "mc_testbench.h"
#include <mc_reset.h>
#include <mc_transactors.h>
#include <mc_scverify.h>
#include <fstream>
#include <string>
#include "ram_fpga_singleport_RF_trans_rsc.h"
#include <mc_monitor.h>
#include "mc_dut_wrapper.h"
#include "ccs_probes.cpp"


class scverify_top : public sc_module
{
public:
   // Interface Ports
   
   // Data objects
   sc_event deadlock_event;
   sc_signal< sc_logic >                      deadlocked;
   sc_event reset_deactivation_event;
   sc_signal< sc_logic >                      rst;
   sc_signal< sc_logic >                      rst_n;
   bool var_trdone;
   sc_clock clk;
   sc_signal< sc_logic >                      TLS_rst;
   sc_signal< sc_logic >                      in_sync;
   sc_signal< sc_logic >                      out_sync;
   sc_signal< sc_logic >                      inout_sync;
   sc_signal< unsigned >                      wait_for_init;
   sc_signal< sc_logic >                      TLS_design_is_idle;
   sc_signal< bool >                          TLS_design_is_idle_reg;
   sc_signal< sc_logic >                      TLS_enable_stalls;
   sc_signal< unsigned short >                TLS_stall_coverage;
   sc_signal< sc_logic >                      catapult_start;
   sc_signal< sc_logic >                      catapult_done;
   sc_signal< sc_logic >                      catapult_ready;
   ccs_probe_monitor* ccs_probe_monitor_INST;
   sc_signal< sc_lv<10> >                     TLS_conv_in_rsc_data_out;
   ccs_sc_logic_to_sc_lv1_adapter CCS_ADAPTOR_conv_in_rsc_re;
   sc_signal< sc_logic >                      TLS_conv_in_rsc_re;
   sc_signal< sc_lv<1> >                      CCS_ADAPTOR_VECTOR_conv_in_rsc_re;
   sc_signal< sc_lv<16> >                     TLS_conv_in_rsc_addr;
   sc_signal< sc_lv<10> >                     TLS_conv_in_rsc_data_in;
   sc_signal< sc_lv<1> >                      TLS_conv_in_rsc_we;
   sc_signal< sc_logic >                      EN_conv_in_rsc_INST_en;
   ccs_sc_logic_to_sc_lv1_adapter CCS_ADAPTOR_conv_out_rsc_we;
   sc_signal< sc_logic >                      TLS_conv_out_rsc_we;
   sc_signal< sc_lv<1> >                      CCS_ADAPTOR_VECTOR_conv_out_rsc_we;
   sc_signal< sc_lv<16> >                     TLS_conv_out_rsc_addr;
   sc_signal< sc_lv<11> >                     TLS_conv_out_rsc_data_in;
   sc_signal< sc_lv<1> >                      TLS_conv_out_rsc_re;
   sc_signal< sc_lv<11> >                     TLS_conv_out_rsc_data_out;
   sc_signal< sc_logic >                      EN_conv_out_rsc_INST_en;
   tlm::tlm_fifo< mc_wait_ctrl > TLS_in_wait_ctrl_fifo_conv_in;
   tlm::tlm_fifo< mgc_sysc_ver_array1D<ac_fixed<10, 10, true, AC_TRN, AC_WRAP >,57600> > TLS_fifo_in_conv_in;
   sc_signal< sc_logic >                      TLS_conv_in_rsc_triosy_lz;
   tlm::tlm_fifo< mc_wait_ctrl > TLS_out_wait_ctrl_fifo_conv_out;
   tlm::tlm_fifo< mgc_sysc_ver_array1D<ac_fixed<11, 11, true, AC_TRN, AC_WRAP >,57600> > TLS_fifo_out_conv_out;
   sc_signal< sc_logic >                      TLS_conv_out_rsc_triosy_lz;
   
   // Named Objects
   
   // Module instance pointers
   ccs_DUT_wrapper *apply_conv_INST;
   mc_programmable_reset *rst_driver;
   catapult_monitor *catapult_monitor_INST;
   ram_fpga_singleport_RF_trans_rsc< 1,57600,10,16,0,1,0,0,0,1,1,1,0 > *conv_in_rsc_INST;
   ram_fpga_singleport_RF_trans_rsc< 2,57600,11,16,0,1,0,0,0,1,1,1,0 > *conv_out_rsc_INST;
   mc_input_transactor<mgc_sysc_ver_array1D<ac_fixed<10, 10, true, AC_TRN, AC_WRAP >,57600>,10,true> *conv_in_transactor;
   mc_trios_input_monitor *trios_monitor_conv_in_INST;
   mc_output_transactor<mgc_sysc_ver_array1D<ac_fixed<11, 11, true, AC_TRN, AC_WRAP >,57600>,11,true> *conv_out_transactor;
   mc_trios_output_monitor *trios_monitor_conv_out_INST;
   testbench *testbench_INST;
   
   // Declare processes (SC_METHOD and SC_THREAD)
   void deadlock_notify();
   void deadlock_watch();
   void generate_sync();
   void generate_reset();
   
   // Constructor
   SC_HAS_PROCESS(scverify_top);
   scverify_top(
      const sc_module_name& name
   )
      : deadlocked("deadlocked")
      , rst("rst")
      , rst_n("rst_n")
      , var_trdone(false)
      , CCS_CLK_CTOR(clk,"clk",10.000000,SC_NS,0.5,0.000000,SC_NS,false)
      , TLS_rst("TLS_rst")
      , in_sync("in_sync")
      , out_sync("out_sync")
      , inout_sync("inout_sync")
      , wait_for_init("wait_for_init")
      , TLS_design_is_idle("TLS_design_is_idle")
      , TLS_design_is_idle_reg("TLS_design_is_idle_reg")
      , TLS_enable_stalls("TLS_enable_stalls")
      , TLS_stall_coverage("TLS_stall_coverage")
      , catapult_start("catapult_start")
      , catapult_done("catapult_done")
      , catapult_ready("catapult_ready")
      , ccs_probe_monitor_INST(NULL)
      , TLS_conv_in_rsc_data_out("TLS_conv_in_rsc_data_out")
      , CCS_ADAPTOR_conv_in_rsc_re("CCS_ADAPTOR_conv_in_rsc_re")
      , TLS_conv_in_rsc_re("TLS_conv_in_rsc_re")
      , CCS_ADAPTOR_VECTOR_conv_in_rsc_re("CCS_ADAPTOR_VECTOR_conv_in_rsc_re")
      , TLS_conv_in_rsc_addr("TLS_conv_in_rsc_addr")
      , TLS_conv_in_rsc_data_in("TLS_conv_in_rsc_data_in")
      , TLS_conv_in_rsc_we("TLS_conv_in_rsc_we")
      , EN_conv_in_rsc_INST_en("EN_conv_in_rsc_INST_en")
      , CCS_ADAPTOR_conv_out_rsc_we("CCS_ADAPTOR_conv_out_rsc_we")
      , TLS_conv_out_rsc_we("TLS_conv_out_rsc_we")
      , CCS_ADAPTOR_VECTOR_conv_out_rsc_we("CCS_ADAPTOR_VECTOR_conv_out_rsc_we")
      , TLS_conv_out_rsc_addr("TLS_conv_out_rsc_addr")
      , TLS_conv_out_rsc_data_in("TLS_conv_out_rsc_data_in")
      , TLS_conv_out_rsc_re("TLS_conv_out_rsc_re")
      , TLS_conv_out_rsc_data_out("TLS_conv_out_rsc_data_out")
      , EN_conv_out_rsc_INST_en("EN_conv_out_rsc_INST_en")
      , TLS_in_wait_ctrl_fifo_conv_in("TLS_in_wait_ctrl_fifo_conv_in",-1)
      , TLS_fifo_in_conv_in("TLS_fifo_in_conv_in",-1)
      , TLS_conv_in_rsc_triosy_lz("TLS_conv_in_rsc_triosy_lz")
      , TLS_out_wait_ctrl_fifo_conv_out("TLS_out_wait_ctrl_fifo_conv_out",-1)
      , TLS_fifo_out_conv_out("TLS_fifo_out_conv_out",-1)
      , TLS_conv_out_rsc_triosy_lz("TLS_conv_out_rsc_triosy_lz")
   {
      // Instantiate other modules
      apply_conv_INST = new ccs_DUT_wrapper(
         "rtl",
         TO_QUOTED_STRING(TOP_HDL_ENTITY)
      );
      apply_conv_INST->conv_in_rsc_data_out(TLS_conv_in_rsc_data_out);
      apply_conv_INST->conv_in_rsc_re(TLS_conv_in_rsc_re);
      apply_conv_INST->conv_in_rsc_addr(TLS_conv_in_rsc_addr);
      apply_conv_INST->conv_out_rsc_we(TLS_conv_out_rsc_we);
      apply_conv_INST->conv_out_rsc_addr(TLS_conv_out_rsc_addr);
      apply_conv_INST->conv_out_rsc_data_in(TLS_conv_out_rsc_data_in);
      apply_conv_INST->clk(clk);
      apply_conv_INST->rst(TLS_rst);
      apply_conv_INST->conv_in_rsc_triosy_lz(TLS_conv_in_rsc_triosy_lz);
      apply_conv_INST->conv_out_rsc_triosy_lz(TLS_conv_out_rsc_triosy_lz);
      
      rst_driver = new mc_programmable_reset(
         "rst_driver",
         120.0,
         0
      );
      rst_driver->reset_out(TLS_rst);
      
      catapult_monitor_INST = new catapult_monitor(
         "Monitor",
         clk,
         true,
         1965902LL,
         1965902LL
      );
      catapult_monitor_INST->rst(rst);
      
      conv_in_rsc_INST = new ram_fpga_singleport_RF_trans_rsc< 1,57600,10,16,0,1,0,0,0,1,1,1,0 > (
         "conv_in_rsc",
         true
      );
      conv_in_rsc_INST->data_out(TLS_conv_in_rsc_data_out);
      conv_in_rsc_INST->re(CCS_ADAPTOR_VECTOR_conv_in_rsc_re);
      conv_in_rsc_INST->addr(TLS_conv_in_rsc_addr);
      conv_in_rsc_INST->clk(clk);
      conv_in_rsc_INST->a_rst(rst);
      conv_in_rsc_INST->s_rst(TLS_rst);
      conv_in_rsc_INST->en(EN_conv_in_rsc_INST_en);
      conv_in_rsc_INST->data_in(TLS_conv_in_rsc_data_in);
      conv_in_rsc_INST->we(TLS_conv_in_rsc_we);
      conv_in_rsc_INST->add_attribute(*(new sc_attribute<double>("CLK_SKEW_DELAY", __scv_hold_time_RSCID_1 )));
      
      conv_out_rsc_INST = new ram_fpga_singleport_RF_trans_rsc< 2,57600,11,16,0,1,0,0,0,1,1,1,0 > (
         "conv_out_rsc",
         true
      );
      conv_out_rsc_INST->we(CCS_ADAPTOR_VECTOR_conv_out_rsc_we);
      conv_out_rsc_INST->addr(TLS_conv_out_rsc_addr);
      conv_out_rsc_INST->data_in(TLS_conv_out_rsc_data_in);
      conv_out_rsc_INST->clk(clk);
      conv_out_rsc_INST->a_rst(rst);
      conv_out_rsc_INST->s_rst(TLS_rst);
      conv_out_rsc_INST->en(EN_conv_out_rsc_INST_en);
      conv_out_rsc_INST->re(TLS_conv_out_rsc_re);
      conv_out_rsc_INST->data_out(TLS_conv_out_rsc_data_out);
      conv_out_rsc_INST->add_attribute(*(new sc_attribute<double>("CLK_SKEW_DELAY", __scv_hold_time_RSCID_2 )));
      
      conv_in_transactor = new mc_input_transactor<mgc_sysc_ver_array1D<ac_fixed<10, 10, true, AC_TRN, AC_WRAP >,57600>,10,true> (
         "transactor_conv_in",
         0,
         10,
         0,
         false
      );
      conv_in_transactor->in_wait_ctrl_fifo(TLS_in_wait_ctrl_fifo_conv_in);
      conv_in_transactor->in_fifo(TLS_fifo_in_conv_in);
      conv_in_transactor->add_attribute(*(new sc_attribute<int>("MC_TRANSACTOR_EVENT", MC_TRANSACTOR_UNDERFLOW | MC_TRANSACTOR_WAIT )));
      conv_in_transactor->bind_clk(clk,true);
      conv_in_transactor->register_block(conv_in_rsc_INST,conv_in_rsc_INST->basename(),TLS_conv_in_rsc_triosy_lz,0,57599,1);
      
      trios_monitor_conv_in_INST = new mc_trios_input_monitor(
         "conv_in_trios_mon"
      );
      trios_monitor_conv_in_INST->trios(TLS_conv_in_rsc_triosy_lz);
      trios_monitor_conv_in_INST->register_mon(catapult_monitor_INST);
      
      conv_out_transactor = new mc_output_transactor<mgc_sysc_ver_array1D<ac_fixed<11, 11, true, AC_TRN, AC_WRAP >,57600>,11,true> (
         "transactor_conv_out",
         0,
         11,
         0
      );
      conv_out_transactor->out_wait_ctrl_fifo(TLS_out_wait_ctrl_fifo_conv_out);
      conv_out_transactor->out_fifo(TLS_fifo_out_conv_out);
      conv_out_transactor->add_attribute(*(new sc_attribute<int>("MC_TRANSACTOR_EVENT", MC_TRANSACTOR_UNDERFLOW | MC_TRANSACTOR_WAIT )));
      conv_out_transactor->bind_clk(clk,true);
      conv_out_transactor->register_block(conv_out_rsc_INST,conv_out_rsc_INST->basename(),TLS_conv_out_rsc_triosy_lz,0,57599,1);
      
      trios_monitor_conv_out_INST = new mc_trios_output_monitor(
         "conv_out_trios_mon"
      );
      trios_monitor_conv_out_INST->trios(TLS_conv_out_rsc_triosy_lz);
      trios_monitor_conv_out_INST->register_mon(catapult_monitor_INST);
      
      testbench_INST = new testbench(
         "user_tb"
      );
      testbench_INST->clk(clk);
      testbench_INST->ccs_conv_in(TLS_fifo_in_conv_in);
      testbench_INST->ccs_wait_ctrl_conv_in(TLS_in_wait_ctrl_fifo_conv_in);
      testbench_INST->ccs_conv_out(TLS_fifo_out_conv_out);
      testbench_INST->ccs_wait_ctrl_conv_out(TLS_out_wait_ctrl_fifo_conv_out);
      testbench_INST->design_is_idle(TLS_design_is_idle_reg);
      testbench_INST->enable_stalls(TLS_enable_stalls);
      testbench_INST->stall_coverage(TLS_stall_coverage);
      
      
      // Register processes
      SC_METHOD(deadlock_notify);
      sensitive << deadlock_event;
      dont_initialize();
      SC_METHOD(deadlock_watch);
      sensitive  << clk;
      dont_initialize();
      SC_METHOD(generate_sync);
      sensitive << clk << rst;
      dont_initialize();
      SC_METHOD(generate_reset);
      sensitive << reset_deactivation_event;
      // Other constructor statements
      testbench::register_end_of_testbench_obj(catapult_monitor_INST);
      #if defined(CCS_SCVERIFY) && defined(CCS_DUT_RTL) && !defined(CCS_DUT_SYSC) && !defined(CCS_SYSC) && !defined(CCS_DUT_POWER)
      ccs_probe_monitor_INST = new ccs_probe_monitor("ccs_probe_monitor");
      ccs_probe_monitor_INST->clk(clk);
      ccs_probe_monitor_INST->rst(rst);
      #endif
      // set seed for random number generator used by wait_ctrl
      mt19937_init_genrand(19650218UL);
      install_observe_foreign_signals();
      CCS_ADAPTOR_conv_in_rsc_re.inSCALAR(TLS_conv_in_rsc_re);
      CCS_ADAPTOR_conv_in_rsc_re.outVECTOR(CCS_ADAPTOR_VECTOR_conv_in_rsc_re);
      EN_conv_in_rsc_INST_en = (0 != 0) ? sc_dt::SC_LOGIC_1 : sc_dt::SC_LOGIC_0;
      CCS_ADAPTOR_conv_out_rsc_we.inSCALAR(TLS_conv_out_rsc_we);
      CCS_ADAPTOR_conv_out_rsc_we.outVECTOR(CCS_ADAPTOR_VECTOR_conv_out_rsc_we);
      EN_conv_out_rsc_INST_en = (0 != 0) ? sc_dt::SC_LOGIC_1 : sc_dt::SC_LOGIC_0;
   }
   
   ~scverify_top()
   {
      delete apply_conv_INST;
      apply_conv_INST = 0;
      delete rst_driver;
      rst_driver = 0;
      delete catapult_monitor_INST;
      catapult_monitor_INST = 0;
      delete conv_in_rsc_INST;
      conv_in_rsc_INST = 0;
      delete conv_out_rsc_INST;
      conv_out_rsc_INST = 0;
      delete conv_in_transactor;
      conv_in_transactor = 0;
      delete trios_monitor_conv_in_INST;
      trios_monitor_conv_in_INST = 0;
      delete conv_out_transactor;
      conv_out_transactor = 0;
      delete trios_monitor_conv_out_INST;
      trios_monitor_conv_out_INST = 0;
      delete testbench_INST;
      testbench_INST = 0;
   }
   
   // C++ class functions
   public:
      void setup_debug() ;
   public:
      void install_observe_foreign_signals() ;
   public:
      void debug(const char *varname, int flags, int count) ;
};
#endif
